#!/bin/bash
# -*- ENCODING: UTF-8 -*-
#
#
#-----------------------------------------------------------------------------------------
# 
# Stop, clean and delete all the Docker-related resources in your sistem.
# [David Rodríguez, @davidjguru] [david.rodriguez@digitalistgroup.com]
# Title: clean_all_docker_related_resources
# Description: Stop and delete all Docker resources: images, containers, volumes, networks. 
#
# davidjguru@gmail.com
# https://www.therussianlullaby.com
# https://davidjguru.github.io/
# https://dev.to/davidjguru
# https://github.com/davidjguru
#-----------------------------------------------------------------------------------------
#

# Initially get a summary about the initial status for all the Docker resources.
docker system df

# Kill (stop) all containers running selected by ID.
docker kill $(docker ps -q)

# Remove all containers with status=exited (stopped).
docker rm $(docker ps -q -f status=exited)

# Delete images by ID.
docker rmi $(docker image ls -q) 

# Remove unused images.
yes |docker image prune

# Remove all volumes.
docker volume prune -f

# Remove all existing networks.
docker network prune -f

# Remove ALL: stopped containers, all networks.
yes |docker system prune -a

# Finally get a full summary about the current Docker resources.
docker system df