name: summerhouse
type: drupal9
docroot: backend_drupal
php_version: "8.0"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: ["backend.summerhouse", "react.summerhouse", "mkdocs.summerhouse"]
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
use_dns_when_possible: true
composer_version: ""
web_environment: []
hooks:
  pre-start:
    # Resolve the extra service files if not exists.
    - exec-host: "([ ! -f ./.ddev/docker-compose.portainer.yaml ] && wget https://raw.githubusercontent.com/drud/ddev-contrib/master/docker-compose-services/portainer/docker-compose.portainer.yaml && mv docker-compose.portainer.yaml ./.ddev/) || (echo 'A portainer service file has been located in your system.')"
    - exec-host: "([ ! -f ./.ddev/docker-compose.frontend_react.yaml ] && mv ./frontend_react/docker-compose.frontend_react.yaml ./.ddev/) || (echo 'A frontend react service file has been located in your system.')"
    - exec-host: "([ ! -f ./.ddev/docker-compose.mkdocs.yaml ] && mv ./mkdocs/docker-compose.mkdocs.yaml ./.ddev/) || (echo 'A MkDocs service file has been located in your system.')"
    - exec-host: "([ -d ./mkdocs/docs ] && cd ./mkdocs/docs && git pull origin) || (git clone https://github.com/davidjguru/summerhouse.wiki.git ./mkdocs/docs)"
    - exec-host: "cp -r ./images/assets/* ./frontend_react/src/assets/"
    - exec-host: "cp -r ./images/assets/* ./backend_drupal/sites/default/files/"
    - exec-host: "sed -i '12s/restart: \"no\"/restart: \"on-failure\"/' ./.ddev/docker-compose.portainer.yaml"
  post-start:
    - exec: sudo echo alias ll=\"ls -lhA\" >> ~/.bashrc
    - exec: sudo echo alias drupalcs="phpcs --standard=Drupal --extensions='php,module,inc,install,test,profile,theme,css,info,txt,md,yml'" >> ~/.bashrc
    - exec: sudo echo  alias drupalcsp="phpcs --standard=DrupalPractice --extensions='php,module,inc,install,test,profile,theme,css,info,txt,md,yml'" >> ~/.bashrc
    - exec: sudo echo alias drupalcbf="phpcbf --standard=Drupal --extensions='php,module,inc,install,test,profile,theme,css,info,txt,md,yml'" >> ~/.bashrc
    # Resolve all dependencies by Composer in container.
    - composer: prepare
    # Install Drupal after start if not installed already.
    - exec: "(drush status bootstrap | grep -q Successful) || (drush site-install --existing-config --site-name=SummerHouse --account-name=admin --account-pass=admin --db-url=mysql://db:db@db/db -y && drush user-add-role 'administrator' admin)"
    - exec: "yes | drush cset system.site uuid $(head -n 1 ./.settings/salt.txt)"
    - exec: "drush cr"
    # Generate 10 new nodes with type article.
    - exec: "drush genc --bundles=article 10"
    # Generate an one-time login for admin and open Drupal in browser.
    - exec-host: "xdg-open $(ddev drush uli admin)" 
    # Launch React frontend in browser.
    - exec-host: "xdg-open http://summerhouse.ddev.site:3000/"
    # Launch MkDocs frontend in browser.
    - exec-host: "xdg-open http://summerhouse.ddev.site:8091/Home/"
    # Enable debugging by-default
    - exec-host: "ddev xdebug on"
  pre-stop:
    - exec-host: "ddev xdebug off"
    - exec: "drush cex -y"
