name: summerhouse
type: drupal9
docroot: backend_drupal
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: ["backend.summerhouse", "react.summerhouse", "mkdocs.summerhouse"]
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
use_dns_when_possible: true
composer_version: ""
web_environment: []
hooks:
  pre-start:
    # Resolve the extra service files if not exists.
    - exec-host: "([ ! -f ./.ddev/docker-compose.portainer.yaml ] && wget https://raw.githubusercontent.com/drud/ddev-contrib/master/docker-compose-services/portainer/docker-compose.portainer.yaml && mv docker-compose.portainer.yaml ./.ddev/) || (echo 'A portainer service file has been located in your system.')"
    - exec-host: "([ ! -f ./.ddev/docker-compose.frontend_react.yaml ] && mv ./frontend_react/docker-compose.frontend_react.yaml ./.ddev/) || (echo 'A frontend react service file has been located in your system.')"
    - exec-host: "([ ! -f ./.ddev/docker-compose.mkdocs.yaml ] && mv ./mkdocs/docker-compose.mkdocs.yaml ./.ddev/) || (echo 'A MkDocs service file has been located in your system.')"
    - exec-host: "(git clone https://github.com/davidjguru/summerhouse.wiki.git ./mkdocs/docs)"
  post-start:
    - exec: sudo echo alias ll=\"ls -lhA\" >> ~/.bashrc
    # Resolve all dependencies by Composer in container.
    - composer: install 
    # Install Drupal after start if not installed already.
    - exec: "(drush status bootstrap | grep -q Successful) || (drush site-install --site-name=SummerHouse --account-name=admin --account-pass=admin --db-url=mysql://db:db@db/db -y && drush user-add-role 'administrator' admin)"
    - exec-host: "yes |ddev drush cset system.site uuid $(head -n 1 ./.settings/salt.txt)"
    - exec: "drush cr"
    - exec-host: "([ $(ddev drush eval 'print_r(array_keys(\\Drupal::entityTypeManager()->getDefinitions()));' | grep shortcut -c) -gt 0 ] && (ddev drush entity:delete shortcut_set) || (echo 'No shortcut entities were found in your system.'))"
    - exec: "drush pmu shortcut -y"
    - exec: "drush cim -y"
    - exec: "drush cr"
    # Generate an one-time login for admin.
    - exec-host: "xdg-open $(ddev drush uli admin)" 
    # Launch React frontend in browser.
    - exec-host: "xdg-open http://summerhouse.ddev.site:3000/"
    # Generate 10 new nodes with type article.
    - exec: "drush genc --bundles=article 10"
    # Enable debugging by-default
    - exec-host: "ddev xdebug on"
    - exec-host: "ddev exec ddev-summerhouse-mkdocs mkdocs build"
  pre-stop:
    - exec-host: "ddev xdebug off"
    - exec: "ddev drush cex -y"
