name: summerhouse
type: drupal9
docroot: web
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
use_dns_when_possible: true
composer_version: ""
web_environment: []
hooks:
  pre-start:
    # Resolve the extra service files if not exists.
    - exec-host: "[ ! -f ./.ddev/docker-compose.portainer.yaml ] && wget https://raw.githubusercontent.com/drud/ddev-contrib/master/docker-compose-services/portainer/docker-compose.portainer.yaml && mv docker-compose.portainer.yaml ./.ddev/"
  post-start:
    - exec: sudo echo alias ll=\"ls -lhA\" >> ~/.bashrc
    # Resolve all dependencies by Composer in container.
    - composer: install 
    # Install Drupal after start if not installed already.
    - exec: "(ddev drush status bootstrap | grep -q Successful) || ddev drush site-install --site-name=SummerHouse --account-name=admin --account-pass=admin --db-url=mysql://db:db@db/db -y"
    - exec: "(ddev drush status bootstrap | grep -q Successful) || ddev drush cex -y)"
    - exec: "(ddev drush status bootstrap | grep -q Successful) || ddev drush user-add-role 'administrator' admin)"
    # Enable all the contrib resources and load config files.
    - exec: "(ddev drush status bootstrap | grep -q Successful) || ddev drush en -y admin_toolbar admin_toolbar_tools admin_toolbar_search admin_toolbar_links_access_filter devel devel_generate"
    - exec: "(ddev drush status bootstrap | grep -q Successful) || ddev drush cim -y"
    - exec: "(ddev drush status bootstrap | grep -q Successful) || ddev drush cr"
    - exec: "ddev xdebug on"
    # Generate an one-time login for admin.
    - exec-host: xdg-open $(ddev drush uli admin) 
