name: summerhouse
type: drupal9
docroot: web
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
use_dns_when_possible: true
composer_version: ""
web_environment: []
hooks:
  pre-start:
    - exec-host: "wget https://raw.githubusercontent.com/drud/ddev-contrib/master/docker-compose-services/portainer/docker-compose.portainer.yaml"
    - exec-host: "mv docker-compose.portainer.yaml .ddev/"
  post-start:
    - composer: install
    - exec: "drush si --site-name=SummerHouse --account-name=admin --account-pass=admin -y"
    - exec: "drush en -y admin_toolbar admin_toolbar_tools admin_toolbar_search admin_toolbar_links_access_filter devel devel_generate"
    - exec: "drush cr"
    - exec-host: "ddev launch" 
