name: PHP Code Sniffer

on: pull_request

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP Code Sniffer
        run: |
          cd ci
          composer require --dev squizlabs/php_codesniffer --with-all-dependencies
          composer require --dev drupal/coder --with-all-dependencies
          yes| composer require --dev dealerdirect/phpcodesniffer-composer-installer

      - name: Check coding standards
        run: |
          cd ci
          vendor/squizlabs/bin/phpcs