site_name: SummerHouse handbook
site_description: Summer House documentation for developers.
theme: material
site_url: http://mkdocs.summerhouse.ddev.site:49150/
dev_addr: '127.0.0.1:8000'
nav:
  - Home: Home.md
  - About Summer House: About-Summer-House.md
  - How to install Summer House: How-to-install-Summer-House.md
  - Know your Summer House installation: Know-your-Summer-House-Installation.md
  - More How-To guides: More-How-To-guides.md
  - Read More: Read-More.md
markdown_extensions:
  - admonition
  - smarty
  - sane_lists